# This is a sample config file that points to a solr server for each environment
development:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/donut-development
test:
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/donut-test
production:
  url: http://127.0.0.1:8983/solr/donut
